[2022-05-31 22:03:15,507] {taskinstance.py:655} INFO - Dependencies all met for <TaskInstance: exchangerate_analysis_ETL_3H.create_table_task 2022-05-31T16:03:11.768350+00:00 [queued]>
[2022-05-31 22:03:15,525] {taskinstance.py:655} INFO - Dependencies all met for <TaskInstance: exchangerate_analysis_ETL_3H.create_table_task 2022-05-31T16:03:11.768350+00:00 [queued]>
[2022-05-31 22:03:15,526] {taskinstance.py:866} INFO - 
--------------------------------------------------------------------------------
[2022-05-31 22:03:15,526] {taskinstance.py:867} INFO - Starting attempt 1 of 1
[2022-05-31 22:03:15,527] {taskinstance.py:868} INFO - 
--------------------------------------------------------------------------------
[2022-05-31 22:03:15,541] {taskinstance.py:887} INFO - Executing <Task(PostgresOperator): create_table_task> on 2022-05-31T16:03:11.768350+00:00
[2022-05-31 22:03:15,544] {standard_task_runner.py:53} INFO - Started process 434 to run task
[2022-05-31 22:03:15,618] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: exchangerate_analysis_ETL_3H.create_table_task 2022-05-31T16:03:11.768350+00:00 [running]> 2e8e423eb79d
[2022-05-31 22:03:15,644] {postgres_operator.py:62} INFO - Executing:  
CREATE TABLE IF NOT EXISTS Rate (pair VARCHAR(250), date VARCHAR(250), rate VARCHAR(250));
[2022-05-31 22:03:15,657] {logging_mixin.py:112} INFO - [2022-05-31 22:03:15,656] {base_hook.py:84} INFO - Using connection to: id: postgres_local. Host: postgres, Port: None, Schema: airflow, Login: airflow, Password: XXXXXXXX, extra: None
[2022-05-31 22:03:15,661] {logging_mixin.py:112} INFO - [2022-05-31 22:03:15,661] {dbapi_hook.py:174} INFO -  
CREATE TABLE IF NOT EXISTS Rate (pair VARCHAR(250), date VARCHAR(250), rate VARCHAR(250));
[2022-05-31 22:03:15,667] {taskinstance.py:1128} ERROR - duplicate key value violates unique constraint "pg_type_typname_nsp_index"
DETAIL:  Key (typname, typnamespace)=(rate, 2200) already exists.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 966, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/usr/local/lib/python3.7/site-packages/airflow/operators/postgres_operator.py", line 65, in execute
    self.hook.run(self.sql, self.autocommit, parameters=self.parameters)
  File "/usr/local/lib/python3.7/site-packages/airflow/hooks/dbapi_hook.py", line 175, in run
    cur.execute(s)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "pg_type_typname_nsp_index"
DETAIL:  Key (typname, typnamespace)=(rate, 2200) already exists.

[2022-05-31 22:03:15,670] {taskinstance.py:1185} INFO - Marking task as FAILED.dag_id=exchangerate_analysis_ETL_3H, task_id=create_table_task, execution_date=20220531T160311, start_date=20220531T220315, end_date=20220531T220315
[2022-05-31 22:03:25,480] {logging_mixin.py:112} INFO - [2022-05-31 22:03:25,478] {local_task_job.py:103} INFO - Task exited with return code 1
